name: TechWars
version: '1.0-SNAPSHOT'
main: org.solocode.techwars.TechWars
api-version: '1.20'
load: STARTUP

commands:
  research:
    description: "Opens the research tree interface"
    usage: "/research"
    aliases: [techtree, rt]
  dev:
    description: "Opens the developer menu"
    usage: "/dev"
  researchadmin:
    description: "Research tree administration commands"
    usage: "/researchadmin <unlock|reset|copy|test> [args...]"
    permission: techwars.admin
  techwars:
    description: "Main plugin commands"
    usage: "/techwars reload"
    permission: techwars.admin
  researchtree:
    description: "Opens the research tree interface"
    usage: "/researchtree"
    aliases: [techtree, rt]
