name: TechWars
version: '1.0-SNAPSHOT'
main: org.solocode.techwars.TechWars
api-version: '1.20'
load: STARTUP

commands:
  testgui:
    description: "This is a test command"
    usage: "/testgui"
  dev:
    description: "Opens the developer menu"
    usage: "/dev"
